In [2]:
import numpy as np 
import pandas as pd 
pw = pd.DataFrame(pd.read_csv('openpowerlifting.csv'))

In [4]:
print(pw.info())


print(pw.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 386414 entries, 0 to 386413
Data columns (total 17 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   MeetID          386414 non-null  int64
 1   Name            386414 non-null  object
 2   Sex             386414 non-null  object
 3   Equipment       386414 non-null  object
 4   Age             147147 non-null  float64
 5   Division        370571 non-null  object
 6   BodyweightKg    384012 non-null  float64
 7   WeightClassKg   382602 non-null  object
 8   Squat4Kg        1243 non-null    float64
 9   BestSquatKg     298071 non-null  float64
 10  Bench4Kg        1962 non-null    float64
 11  BestBenchKg     356364 non-null  float64
 12  Deadlift4Kg     2800 non-null    float64
 13  BestDeadliftKg  317847 non-null  float64
 14  TotalKg         363237 non-null  float64
 15  Place           385322 non-null  object
 16  Wilks           362194 non-null  float64
dtypes: float64(10), int64(1), object(6)
memory usage: 50.1+ MB
None
   MeetID              Name Sex   Equipment   Age     Division  BodyweightKg  \
0       0  Angie Belk Terry   F       Wraps  47.0    Mst 45-49         59.60
1       0       Dawn Bogart   F  Single-ply  42.0    Mst 40-44         58.51
2       0       Dawn Bogart   F  Single-ply  42.0  Open Senior         58.51
3       0       Dawn Bogart   F         Raw  42.0  Open Senior         58.51
4       0      Destiny Dula   F         Raw  18.0   Teen 18-19         63.68

  WeightClassKg  Squat4Kg  BestSquatKg  Bench4Kg  BestBenchKg  Deadlift4Kg  \
0            60       NaN        47.63       NaN        20.41          NaN
1            60       NaN       142.88       NaN        95.25          NaN
2            60       NaN       142.88       NaN        95.25          NaN
3            60       NaN          NaN       NaN        95.25          NaN
4          67.5       NaN          NaN       NaN        31.75          NaN

   BestDeadliftKg  TotalKg Place   Wilks
0           70.31   138.35     1  155.05
1          163.29   401.42     1  456.38
2          163.29   401.42     1  456.38
3             NaN    95.25     1  108.29
4           90.72   122.47     1  130.47

In [7]:
len(pd.unique(pw['MeetID']))

# There are 8482 meetings taken into consideration

8482

In [18]:
print('The number of 4th attempts at squat is: ',len(pw['Squat4Kg'])-pw['Squat4Kg'].isna().sum())

The number of 4th attempts at squat is:  1243

In [20]:
print('The number of 4th attempts at bench is: ',len(pw['Bench4Kg'])-pw['Bench4Kg'].isna().sum())

The number of 4th attempts at bench is:  1962

In [25]:
print('The number of 4th attempts at deadlift is: ',len(pw['Deadlift4Kg'])-pw['Deadlift4Kg'].isna().sum(),'\n')
print('The athletes are more likely to try for a 4th attempt on the deadlift, more than double the times they attempt at an additional squat.')

The number of 4th attempts at deadlift is:  2800

The athletes are more likely to try for a 4th attempt on the deadlift, more than double the times they attempt at an additional squat.

In [28]:
pw1=pw.drop('Deadlift4Kg',axis=1)
pw1.head()

,MeetID,Name,Sex,Equipment,Age,Division,BodyweightKg,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,BestDeadliftKg,TotalKg,Place,Wilks
0,0,Angie Belk Terry,F,Wraps,47.0,Mst 45-49,59.60,60,NaN,47.63,NaN,20.41,70.31,138.35,1,155.05
1,0,Dawn Bogart,F,Single-ply,42.0,Mst 40-44,58.51,60,NaN,142.88,NaN,95.25,163.29,401.42,1,456.38
2,0,Dawn Bogart,F,Single-ply,42.0,Open Senior,58.51,60,NaN,142.88,NaN,95.25,163.29,401.42,1,456.38
3,0,Dawn Bogart,F,Raw,42.0,Open Senior,58.51,60,NaN,NaN,NaN,95.25,NaN,95.25,1,108.29
4,0,Destiny Dula,F,Raw,18.0,Teen 18-19,63.68,67.5,NaN,NaN,NaN,31.75,90.72,122.47,1,130.47

In [30]:
pw1=pw.drop(['Bench4Kg','Squat4Kg','Deadlift4Kg'],axis=1)
pw1.head()

,MeetID,Name,Sex,Equipment,Age,Division,BodyweightKg,WeightClassKg,BestSquatKg,BestBenchKg,BestDeadliftKg,TotalKg,Place,Wilks
0,0,Angie Belk Terry,F,Wraps,47.0,Mst 45-49,59.60,60,47.63,20.41,70.31,138.35,1,155.05
1,0,Dawn Bogart,F,Single-ply,42.0,Mst 40-44,58.51,60,142.88,95.25,163.29,401.42,1,456.38
2,0,Dawn Bogart,F,Single-ply,42.0,Open Senior,58.51,60,142.88,95.25,163.29,401.42,1,456.38
3,0,Dawn Bogart,F,Raw,42.0,Open Senior,58.51,60,NaN,95.25,NaN,95.25,1,108.29
4,0,Destiny Dula,F,Raw,18.0,Teen 18-19,63.68,67.5,NaN,31.75,90.72,122.47,1,130.47

In [ ]:
pw1.